name: 'Lint'
description: 'Lint TypeScript and Python code'

inputs:
  node_version:
    description: 'Version of Node to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'

    - name: Install Node dependencies
      run: npm ci
      shell: bash

    - name: Lint TypeScript code
      run: npm run lint
      shell: bash

    - name: Check TypeScript format
      run: npm run format-check
      shell: bash

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-lint-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-lint-

    - name: Upgrade Pip
      run: python -m pip install -U pip
      shell: bash

    - name: Install wheel and nox
      run: python -m pip install wheel nox
      shell: bash

    # This will install libraries to a target directory.
    - name: Install bundled python libraries
      run: python -m nox --session install_bundled_libs
      shell: bash

    - name: Check linting and formatting
      run: python -m nox --session lint
      shell: bash
